CC=g++
CFLAGS= -g -o
main: 
	$(CC) $(CFLAGS) multiples_calificaciones_por_estudiante  main.cc multiples_calificaciones_por_estudiante.cc multiples_calificaciones_por_estudiante.h  

.PHONY: clean
clean:
	rm -rf multiples_calificaciones_por_estudiante multiples_calificaciones_por_estudiante.h.gch
	