CC=g++
CFLAGS= -g -o
main: 
	$(CC) $(CFLAGS) automata_finito  p05_automata_simulator.cc Estado.cc Estado.h Alfabeto.cc Alfabeto.h ConjuntoEstados.cc ConjuntoEstados.h 

.PHONY: clean
clean:
	rm -rf automata_finito Alfabeto.h.gch ConjuntoEstados.h.gch Estado.h.gch