CC=g++
CFLAGS= -g -o
main: 
	$(CC) $(CFLAGS) calificacion_unica_por_estudiante  main.cc calificacion_unica_por_estudiante.cc calificacion_unica_por_estudiante.h  

.PHONY: clean
clean:
	rm -rf calificacion_unica_por_estudiante calificacion_unica_por_estudiante.h.gch
	