CC=g++
CFLAGS= -g -o
main: 
	$(CC) $(CFLAGS) NFA_To_DFA main.cc Estado.cc Estado.h Alfabeto.cc Alfabeto.h Automata.cc Automata.h 

.PHONY: clean
clean:
	rm -rf NFA_To_DFA Alfabeto.h.gch Automata.h.gch Estado.h.gch